package cl.manuel.addressbook_app;

/*CLASE ENCARGADA DE GESTIONAR EL DESPLIEGUE DE INFO AL TOCAR UN CONTACTO,
* ADEMÁS DE MOSTRAR Y GESTIONAR LOS ÍTEMS DE MENÚ DE LA APPBAR*/

public class FDetalle {
}
